export const TEAM_NAME_ALIASES: Record<string, string[]> = {
  'Michigan St': ['Michigan State', 'Michigan State Spartans'],
  "St John's": ["St. John's", "St. John's Red Storm", "Saint John's"],
  'Ohio State': ['Ohio State Buckeyes'],
  'CA Baptist': ['Cal Baptist', 'California Baptist', 'Cal Baptist Lancers'],
  'North Dakota St': ['North Dakota State', 'North Dakota St.'],
  'South Florida': ['USF', 'South Florida Bulls'],
  'Northern Iowa': ['Northern Iowa Panthers', 'UNI'],
  "Saint Mary's": ["Saint Mary's Gaels", "St. Mary's", "Saint Mary's (CA)"],
  'BYU': ['Brigham Young', 'BYU Cougars'],
  "Hawai'i": ['Hawaii', "Hawai'i Rainbow Warriors"],
  'Kennesaw St': ['Kennesaw State', 'Kennesaw State Owls'],
  'Miami': ['Miami Hurricanes', 'Miami (FL)'],
  'Miami (OH)': ['Miami (OH) RedHawks', 'Miami Ohio', 'Miami RedHawks'],
  'High Point': ['High Point Panthers'],
  'VCU': ['Virginia Commonwealth', 'VCU Rams'],
  'McNeese': ['McNeese State', 'McNeese Cowboys'],
  'Prairie View A&M': ['Prairie View', 'Prairie View A&M Panthers', 'Prairie View A&amp;M'],
  'Texas A&M': ['Texas A&M Aggies', 'Texas A&amp;M'],
  'Wright St': ['Wright State', 'Wright State Raiders'],
  'Tennessee St': ['Tennessee State'],
  'Long Island': ['Long Island University', 'LIU', 'LIU Sharks'],
  'Utah State': ['Utah State Aggies'],
  'Iowa State': ['Iowa State Cyclones'],
  'Texas Tech': ['Texas Tech Red Raiders'],
  'UCF': ['Central Florida', 'UCF Knights'],
  'TCU': ['TCU Horned Frogs'],
  'Queens': ['Queens University', 'Queens University Royals'],
  'UCLA': ['UCLA Bruins'],
  'Penn': ['Pennsylvania', 'Pennsylvania Quakers', 'Penn Quakers'],
  'Duke': ['Duke Blue Devils'],
  'Nebraska': ['Nebraska Cornhuskers'],
  'Louisville': ['Louisville Cardinals'],
  'Wisconsin': ['Wisconsin Badgers'],
  'Siena': ['Siena Saints'],
  'Vanderbilt': ['Vanderbilt Commodores'],
  'Arkansas': ['Arkansas Razorbacks'],
  'North Carolina': ['North Carolina Tar Heels', 'UNC'],
  'Michigan': ['Michigan Wolverines'],
  'Howard': ['Howard Bison'],
  'Texas': ['Texas Longhorns'],
  'Illinois': ['Illinois Fighting Illini'],
  'Idaho': ['Idaho Vandals'],
  'Troy': ['Troy Trojans'],
  'Gonzaga': ['Gonzaga Bulldogs'],
  'Houston': ['Houston Cougars'],
  'Florida': ['Florida Gators'],
  'Arizona': ['Arizona Wildcats'],
  'Virginia': ['Virginia Cavaliers'],
  'Alabama': ['Alabama Crimson Tide'],
  'Purdue': ['Purdue Boilermakers'],
  'Kansas': ['Kansas Jayhawks'],
  'Tennessee': ['Tennessee Volunteers'],
  'Kentucky': ['Kentucky Wildcats'],
  'Clemson': ['Clemson Tigers'],
  'Iowa': ['Iowa Hawkeyes'],
  'Missouri': ['Missouri Tigers', 'Mizzou'],
  'Georgia': ['Georgia Bulldogs'],
  'Santa Clara': ['Santa Clara Broncos'],
  'Akron': ['Akron Zips'],
  'Hofstra': ['Hofstra Pride'],
  'Furman': ['Furman Paladins'],
  'Saint Louis': ['Saint Louis Billikens', 'St. Louis', 'St. Louis Billikens'],
  'UConn': ['Connecticut', 'Connecticut Huskies', 'UConn Huskies'],
}

export const ROUND_NAMES: Record<number, string> = {
  0: 'First Four',
  1: 'Round of 64',
  2: 'Round of 32',
  3: 'Sweet 16',
  4: 'Elite 8',
  5: 'Final Four',
  6: 'Championship',
}
